### PR TITLE
Add vertical and horizontal vane position controls

### PR DESCRIPTION
**Pull request by seime**
- Add vertical and horizontal vane selects as done for Panasonic pumps; https://github.com/DomiStyle/esphome-panasonic-ac 
- Add `HORIZONTAL` and `BOTH` swing mode options in additon to `OFF` and `VERTICAL`
- Fix logging bug causing ESP to crash

Note: This PR is a bit rough around the edges - it has been almost 2 decades since I last worked with C/C++
- I've tried to reformat the code according to the Google style (as used by ESPHome), but actually not sure whether VSCode did it or applied another format (not familiar with C codestyles)
- VSCode also decided to reformat the README.md when I updated it.

Frankly I do not expect this PR to get merged especially due to the number of changed lines by the formatter, but I though maybe some users would like to try it out as it the features have been requested in several issues.

### CODE REVIEW

**Comment by jamescadd** [comment]
It looks like your formatting made changes to lines you didn't actually change. Would be easier to read without this. Thanks for the PR and I'd be happy to test if it looks like @geoffdavis would support it getting merged!

**Comment by seime** [comment]
> It looks like your formatting made changes to lines you didn't actually change. Would be easier to read without this. Thanks for the PR and I'd be happy to test if it looks like @geoffdavis would support it getting merged!

Yes, I am aware. The formatter formatted everything as I wrote in the initial comment.
You can test it by changing the ESPHome source to https://github.com/seime/esphome-mitsubishiheatpump

**Comment by balu-** [comment]
I like to have that feature but unfortunately the pull request is so messy that i won't get my hope up

**Comment by geoffdavis** [comment]
Closing in lieu of #109

**Pull request closed without merging**
