### PR TITLE
Update SwiCago/HeatPump to latest commit

### LINKED ISSUE #70: Upgrade to SwiCago/HeatPump version 1.0.0
It looks like the SwiCago/HeatPump library has been updated a bit, and is now at a 1.0.0 release. We should support that version. There are API changes, so some work will need to be done to this library.

### PR DESCRIPTION
**Pull request by grischard**
Fixes #70. Difference is https://github.com/SwiCago/HeatPump/pull/182.

### CODE REVIEW

**Comment by grischard** [comment]
Well, compared to #68 it compiles at least. I'll try it on an actual unit soon.

@juan11perez and @dwildstr, you've shown interest in this in the past, would you like to test it too, by temporarily changing the `external_components:` part to `- source: github://grischard/esphome-mitsubishiheatpump@Update-SwiCago/HeatPump` ?

**Comment by juan11perez** [comment]
@grischard 
Sure, thanks.
It's only the firmware rebuild?
I saw in your previous note  pin change.

**Comment by grischard** [comment]
@juan11perez yes, a simple rebuild telling esphome to grab the component from my forked branch instead of the main one.

**Comment by dwildstr** [comment]
I've installed it on my two pumps. For reference I'm running generic-knockoff D1 Mini boards, controlling MSZ-GE09NA pumps, and using ESPHome 2022.10.1 and controlling them with Home Assistant. Thus far it seems to work OK, but I haven't really done much beyond installing it.

**Comment by juan11perez** [comment]
@grischard I've installed on one of my horizontal ducted units (PEY-SM36JAl ) and it's running fine.
I'm using an ESP32S. 

I installed ESP32U (with antenna) in other units and just couldn't get the geoffdavies repo to work.
It would send the commands, but it could not read the feedback, and I tried all 3 UART options and combinations.

However, I installed  [Tasmota](https://isaiahchia.com/2022/06/16/integrating-mitsubishi-air-con-hvac-with-home-assistant-via-nodemcutasmota/) in the same boards and it's working very well.

I'll try your repo on one of these ESP32U and revert.

**Comment by grischard** [comment]
I had no idea Tasmota had support for these Mitsubishi units! I don't expect the code changes in https://github.com/SwiCago/HeatPump/pull/182 to make a big difference to your issue, but am curious how it goes.

**Comment by geoffdavis** [comment]
Looking at this now. Let me make a test on one of my units.

**Comment by geoffdavis** [comment]
@grischard As far as I can tell, this looks like it works ok.

For some reason I thought the 1.0.0 API of SwiCago/HeatPump made some big API changes. My initial tests at least didn't work, but I must have had fat fingers.

I'll go ahead and mark this ready for review and merge it.

**Pull request merged**
